/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedConsoleIndexRouteImport } from './routes/_authenticated/console.index'
import { Route as AuthenticatedConsoleCasesRouteImport } from './routes/_authenticated/console.cases'
import { Route as AuthenticatedConsoleNetworkRouteImport } from './routes/_authenticated/console.network'
import { Route as AuthenticatedConsoleReportsRouteImport } from './routes/_authenticated/console.reports'
import { Route as AuthenticatedConsoleSettingsRouteImport } from './routes/_authenticated/console.settings'
import { Route as AuthenticatedConsoleRecordsRecordIdRouteImport } from './routes/_authenticated/console.records.$recordId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleCasesRoute =
  AuthenticatedConsoleCasesRouteImport.update({
    id: '/cases',
    path: '/cases',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleNetworkRoute =
  AuthenticatedConsoleNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleReportsRoute =
  AuthenticatedConsoleReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSettingsRoute =
  AuthenticatedConsoleSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleRecordsRecordIdRoute =
  AuthenticatedConsoleRecordsRecordIdRouteImport.update({
    id: '/records/$recordId',
    path: '/records/$recordId',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/console': typeof AuthenticatedConsoleRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/console/cases': typeof AuthenticatedConsoleCasesRoute
  '/console/network': typeof AuthenticatedConsoleNetworkRoute
  '/console/reports': typeof AuthenticatedConsoleReportsRoute
  '/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
  '/console/records/$recordId': typeof AuthenticatedConsoleRecordsRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/console/cases': typeof AuthenticatedConsoleCasesRoute
  '/console/network': typeof AuthenticatedConsoleNetworkRoute
  '/console/reports': typeof AuthenticatedConsoleReportsRoute
  '/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
  '/console/records/$recordId': typeof AuthenticatedConsoleRecordsRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/console/cases': typeof AuthenticatedConsoleCasesRoute
  '/_authenticated/console/network': typeof AuthenticatedConsoleNetworkRoute
  '/_authenticated/console/reports': typeof AuthenticatedConsoleReportsRoute
  '/_authenticated/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
  '/_authenticated/console/records/$recordId': typeof AuthenticatedConsoleRecordsRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/console'
    | '/auth/callback'
    | '/console/cases'
    | '/console/network'
    | '/console/reports'
    | '/console/settings'
    | '/console/'
    | '/console/records/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/auth/callback'
    | '/console/cases'
    | '/console/network'
    | '/console/reports'
    | '/console/settings'
    | '/console'
    | '/console/records/$recordId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/reset-password'
    | '/_authenticated/console'
    | '/auth/callback'
    | '/_authenticated/console/cases'
    | '/_authenticated/console/network'
    | '/_authenticated/console/reports'
    | '/_authenticated/console/settings'
    | '/_authenticated/console/'
    | '/_authenticated/console/records/$recordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/cases': {
      id: '/_authenticated/console/cases'
      path: '/cases'
      fullPath: '/console/cases'
      preLoaderRoute: typeof AuthenticatedConsoleCasesRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/network': {
      id: '/_authenticated/console/network'
      path: '/network'
      fullPath: '/console/network'
      preLoaderRoute: typeof AuthenticatedConsoleNetworkRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/reports': {
      id: '/_authenticated/console/reports'
      path: '/reports'
      fullPath: '/console/reports'
      preLoaderRoute: typeof AuthenticatedConsoleReportsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/settings': {
      id: '/_authenticated/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof AuthenticatedConsoleSettingsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/records/$recordId': {
      id: '/_authenticated/console/records/$recordId'
      path: '/records/$recordId'
      fullPath: '/console/records/$recordId'
      preLoaderRoute: typeof AuthenticatedConsoleRecordsRecordIdRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
  }
}

interface AuthenticatedConsoleRouteChildren {
  AuthenticatedConsoleCasesRoute: typeof AuthenticatedConsoleCasesRoute
  AuthenticatedConsoleNetworkRoute: typeof AuthenticatedConsoleNetworkRoute
  AuthenticatedConsoleReportsRoute: typeof AuthenticatedConsoleReportsRoute
  AuthenticatedConsoleSettingsRoute: typeof AuthenticatedConsoleSettingsRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
  AuthenticatedConsoleRecordsRecordIdRoute: typeof AuthenticatedConsoleRecordsRecordIdRoute
}

const AuthenticatedConsoleRouteChildren: AuthenticatedConsoleRouteChildren = {
  AuthenticatedConsoleCasesRoute: AuthenticatedConsoleCasesRoute,
  AuthenticatedConsoleNetworkRoute: AuthenticatedConsoleNetworkRoute,
  AuthenticatedConsoleReportsRoute: AuthenticatedConsoleReportsRoute,
  AuthenticatedConsoleSettingsRoute: AuthenticatedConsoleSettingsRoute,
  AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
  AuthenticatedConsoleRecordsRecordIdRoute:
    AuthenticatedConsoleRecordsRecordIdRoute,
}

const AuthenticatedConsoleRouteWithChildren =
  AuthenticatedConsoleRoute._addFileChildren(AuthenticatedConsoleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleRoute: AuthenticatedConsoleRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
